@startuml
'https://plantuml.com/class-diagram


class Jugador {
    -- Atributs --
    - nom: String
    - gols: Int
    - posicio:IntArray
    - assistencies: Int
    -- Mètodes --
    + constructor(String, Int, IntArray, Int)
    + marcarGol(gols: Int): Int
    + ferAssistencia(assistencies: Int): Int
}

class Entrenador{
    -- Atributs --
    - nom: String
    - equip: Equip
    -- Mètodes --
    + constructor(String, Equip)
    + entrenar()
}

Equip *--Jugador
class Equip {
    -- Atributs --
    - nom: String
    - entrenador: Entrenador
    - jugadors: List<Jugador>
    -- Mètodes --
    + constructor(String, String, List<Jugador>)
    + afegirJugador(jugadors: List<Jugador>): List<Jugador>
    + sumarPuntsEquip(): Int
}

@enduml
