@startuml
'https://plantuml.com/class-diagram

enum Tipus {
    electric
    combustible
}

enum Marxes{
    automatic
    manual
}
class Cotxe{
    -- Atributs --
    - nom: String
    - motor: Tipus
    - marxes: Marxes
    -- Mètodes --
    + constructor(String, Tipus, Marxes, Tipus)
    + arrancar()
    + accelerar()
    + frenar()
}

class Instructor{
    -- Atributs --
    - nom: String
    - anysExperiencia: Int
    - cotxeUtilitzat: Cotxe
    -- Mètodes --
    + constructor(String, Int, Cotxe)
    + assignarPractica(alumne: Alumne)
    + consultarTotalPractiques(): Int
    + getPractriquesFetes(): Int
    + teoricaAprovada(): Boolean
}

class Alumne {
    -- Atributs --
    - nom: String
    - edat: Int
    - teoricaAprovada: Boolean
    - practriquesFetes: Int
    -- Mètodes --
    + constructor(String, Int, Boolean, Int)
    + sumarPractica(practriquesFetes: Int): Int
    + getPractriquesFetes(): Int
    + setAprovarTeorica(teoricaAprovada: Boolean)
}

class Practica {
    -- Atributs --
    - profesor: Instructor
    - alumne: Alumne
    - data: LocalDate
    - durada: Int
    -- Mètodes --
    + constructor(Instructor, Alumne, LocalDate)
    + setDurada(durada: Int)
}
Instructor --* Practica
Instructor --* Cotxe
Alumne --* Practica
Tipus --*Cotxe
Marxes --* Cotxe

@enduml
